name: Build and test

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            glslang-tools \
            libglfw3-dev \
            libglm-dev \
            libvulkan-dev \
            ninja-build

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug

      - name: Test
        run: ctest --preset debug
